# Generated by Django 5.2.8 on 2025-12-09 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meal',
            table='menu',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
